name: Ruby

on:
   push:
     branches:
     - master
   pull_request:
     branches:
     - master

jobs:
  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: generate message to maybe troll you
      id: ohrly
      uses: jpemberthy/oh-rly@master
    - name: maybe comment on the PR
      uses: unsplash/comment-on-pr@master
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
         msg: ${{ setps.ohrly.outputs.message }} 
    - uses: actions/checkout@master
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        version: 2.6.x
    - name: Build and test
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec ruby meme_test.rb
